---
author: "par Lucie HUBERT"
title: "Programme d'entraînement pour `r input$client_name`"
output:
  pdf_document:
    extra_dependencies: ["booktabs", "fancyhdr"]
date: "`r format(Sys.Date(), '%d %B %Y')`"
params:
  client_name: NULL
  exercices: NULL
  exercise_choices: NULL
  series_summary_par_semaine: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Fonction pour créer un tableau récapitulatif de la semaine type d'entraînement
creer_tableau_recapitulatif <- function(exercise_choices) {
  jours <- c("Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche")
  
  # Vérifier et attribuer une activité par défaut si nécessaire
  for (jour in jours) {
    if (is.null(exercise_choices[[jour]])) {
      exercise_choices[[jour]] <- "Repos"
    }
  }
  
  # Création du tableau récapitulatif avec une seule ligne "Activité"
  tableau <- matrix("", nrow = 1, ncol = length(jours), dimnames = list("Activité", jours))
  
  # Remplissage des activités dans la seule ligne ("Activité")
  for (activity in seq_along(jours)) {
    jour <- jours[activity]
    tableau["Activité", jour] <- exercise_choices[[jour]]
  }
  
  return(tableau)
}

# Fonction pour afficher les exercices pour chaque séance
afficher_exercices <- function(seance, exercices) {
  if (length(exercices) > 0 && any(sapply(exercices, function(x) is.list(x) && length(x) > 0))) {
    cat(paste0("### Séance ", seance, "\n\n"))
    
    for (i in seq_along(exercices)) {
      if (is.list(exercices[[i]]) && length(exercices[[i]]) > 0) {
        cat("Exercice ", i, " : \n")
        cat("\\textcolor{red}{", exercices[[i]]$mouvement, "}\n")
        cat("(", exercices[[i]]$muscle, ")\n")
        cat("\\textcolor{red}{", exercices[[i]]$series, "}")
        cat("\\textcolor{red}{*", exercices[[i]]$repetitions_min, " à ", exercices[[i]]$repetitions_max, " répétitions}\n\n")
      }
    }
  }
}
```

# Semaine type d'entraînement
```{r echo=FALSE, results='asis'}
tableau_recap <- creer_tableau_recapitulatif(params$exercise_choices)
print(kable(tableau_recap, format = "latex", booktabs = TRUE))
```

# Répartition des séances
```{r echo=FALSE, results='asis'}
for (seance in seq_along(params$exercices)) {
  afficher_exercices(seance, params$exercices[[seance]])
}
```

# Répartition du volume d'entraînement par groupe musculaire
```{r echo=FALSE, results='asis'}
if ("series_summary_par_semaine" %in% names(params$exercices)) {
  summary_df <- params$exercices$series_summary_par_semaine

# Création du tableau en LaTeX avec kable
table_output <- kable(summary_df, format = "latex", booktabs = TRUE)

# Afficher le tableau LaTeX
cat(table_output)

# Création du graphique pie-chart
pie_chart <- ggplot(summary_df, aes(x = "", y = Series, fill = Muscle)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(fill = "Muscle") +
  theme_void() +
  theme(legend.position = "right")

# Affichage côte à côte avec grid.arrange
grid.arrange(pie_chart, ncol = 1, heights = c(0.5, 0.5))
}
```
